# Generated by Django 4.2.7 on 2025-03-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cvv',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
