# Generated by Django 4.2.7 on 2025-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
